// ------------------------------------------------------------
// App/SimulatorEngine.cs
// ------------------------------------------------------------
using System;
using System.Collections.Generic;
using SportSimulator.Models;
using SportSimulator.Profiles;
using SportSimulator.Tracking;
using SportSimulator.Transport;
using SportSimulator.Vision;
using SportSimulator.Vision.Calibration;

namespace SportSimulator.App
{
    public class SimulatorEngine : IDisposable
    {
        private readonly ICameraManager    _cameras;
        private readonly BallDetector      _detector = new();
        private readonly KalmanBallTracker _tracker = new();
        private readonly SportProfileRegistry _registry = new();
        private readonly StereoRectifier _rectifier = new();
        private readonly Triangulator    _triangulator = new();

        /// <summary>
        /// Production constructor — uses the real Spinnaker-backed CameraManager.
        /// Only available on net48 (Spinnaker SDK is not present on net10.0).
        /// </summary>
#if NET48
        public SimulatorEngine() : this(new CameraManager()) { }
#endif

        /// <summary>
        /// Injection constructor — pass a MockCameraManager (or any ICameraManager)
        /// for unit tests on machines without the Spinnaker SDK.
        /// </summary>
        public SimulatorEngine(ICameraManager cameras)
        {
            _cameras = cameras;
            _activeProfile = _registry.GetOrDefault("soccer");
        }

        private UdpTransport? _udp;
        private SportProfile  _activeProfile = null!; // set in constructor before use
        private bool _running;

        // Latest detection from each camera, keyed by camera index
        private readonly Dictionary<int, DetectionResult> _pending = new();
        private readonly object _pendingLock = new();

        // Max frames the Kalman filter will predict forward without any detection.
        // Set from SportProfile.KalmanCoastFrames on each profile switch.
        private int _maxCoastFrames = 5;
        private int _coastFrames = 0;

        // Calibration file path — generated by running StereoCalibrator once.
        // ⚠️ SETUP TODO — run the calibration routine before first real use:
        //   1. Print a 9×6 checkerboard with 25mm squares
        //   2. Hold it at various positions/angles visible to both cameras
        //   3. Call StereoCalibrator.AddFramePair() for 15+ positions
        //   4. Call StereoCalibrator.Calibrate() — outputs this JSON file
        //   5. Aim for RMS reprojection error < 1.0px (< 0.5px is excellent)
        // Until this file exists, CreateDefaults() is used as a fallback.
        private const string CalibPath = "stereo_calibration.json";

        public void Start(string unityIp = "127.0.0.1", int sendPort = 7100, int listenPort = 7101)
        {
            LoadCalibration();

            _udp = new UdpTransport(unityIp, sendPort, listenPort);
            _udp.ProfileCommandReceived += OnProfileCommand;
            _udp.StartListening();

            _cameras.Initialize(_activeProfile.SportId);
            ApplyProfile(_activeProfile);
            _cameras.StartCapture();

            _running = true;
            Console.WriteLine("[Engine] Running. Waiting for stereo frame pairs...");
            ProcessLoop();
        }

        private void LoadCalibration()
        {
            StereoCalibrationData cal;
            if (System.IO.File.Exists(CalibPath))
            {
                cal = StereoCalibrationData.LoadFromFile(CalibPath);
                Console.WriteLine($"[Engine] Loaded calibration from {CalibPath}");
            }
            else
            {
                // ⚠️ SETUP TODO — using estimated defaults until calibration is run.
                // Update baselineMetres to 2 × your measured centre-to-edge distance.
                // e.g. if centre-to-edge = 350mm → 0.70, 420mm → 0.84
                cal = StereoCalibrationData.CreateDefaults(baselineMetres: 0.70);
                Console.WriteLine("[Engine] WARNING: Using default calibration. Run StereoCalibrator for accuracy.");
            }

            _rectifier.Build(cal);
            _triangulator.Configure(cal);
        }

        private void OnProfileCommand(ProfileSelectCommand cmd)
        {
            var p = _registry.GetOrDefault(cmd.SportId);
            ApplyProfile(p);
            Console.WriteLine($"[Engine] Profile switched to: {p.DisplayName}");
        }

        private void ApplyProfile(SportProfile p)
        {
            _activeProfile  = p;
            _detector.SetProfile(p);
            _tracker.Configure(p);
            _cameras.ApplyProfile(p.SportId);
            _maxCoastFrames = p.KalmanCoastFrames;
            Console.WriteLine($"[Engine] Coast window set to {_maxCoastFrames} frames for {p.DisplayName}");
        }

        private void ProcessLoop()
        {
            while (_running)
            {
                // Drain all frames that arrived since last iteration
                DetectionResult? det0 = null, det1 = null;

                while (_cameras.FrameQueue.TryTake(out var frame, 5))
                {
                    var det = _detector.Detect(frame);
                    if (!det.Found) continue;
                    if (det.CameraIndex == 0) det0 = det;
                    else                      det1 = det;
                }

                TriangulatedPoint? pt3d = null;

                // ── Tier 1 / 2: both cameras this cycle ─────────────────────────
                if (det0 != null && det1 != null)
                {
                    pt3d = _triangulator.TriangulateStereo(det0.Center, det1.Center);

                    // If stereo disagreed and fell to monocular internally,
                    // enrich it with the Kalman's last Z before sending
                    if (pt3d.Tier == TriangulationTier.Monocular && pt3d.Z == 0)
                    {
                        var (kx, ky, kz, _, _, _) = _tracker.LastState;
                        pt3d = _triangulator.TriangulateMonocular(det0.Center, kz);
                    }

                    _coastFrames = 0;
                }
                // ── Tier 3: only one camera this cycle ──────────────────────────
                else if (det0 != null || det1 != null)
                {
                    var single = (det0 ?? det1)!;
                    var (_, _, kz, _, _, _) = _tracker.LastState;
                    pt3d = _triangulator.TriangulateMonocular(single.Center, kz);
                    _coastFrames = 0;
                }
                // ── Tier 4: no detection — Kalman coast ─────────────────────────
                else
                {
                    _coastFrames++;
                    if (_coastFrames > _maxCoastFrames) continue; // ball gone

                    var (kx, ky, kz, _, _, _) = _tracker.LastState;
                    float coastConf = Math.Max(0.05f, 0.3f - _coastFrames * (0.25f / _maxCoastFrames));
                    pt3d = new TriangulatedPoint
                    {
                        X = kx, Y = ky, Z = kz,
                        Confidence = coastConf,
                        Tier       = TriangulationTier.KalmanOnly,
                        TierReason = $"Coasting frame {_coastFrames}/{_maxCoastFrames}"
                    };
                }

                // Flip Y: OpenCV Y-down → Unity Y-up
                float mx = pt3d.X, my = -pt3d.Y, mz = pt3d.Z;

                // Only feed real measurements into Kalman; coast uses predict-only
                (float x, float y, float z, float vx, float vy, float vz) state;
                if (pt3d.Tier == TriangulationTier.KalmanOnly)
                    state = _tracker.Predict();
                else
                    state = _tracker.Update(mx, my, mz);

                var (sx, sy, sz, svx, svy, svz) = state;
                float speed       = MathF.Sqrt(svx*svx + svy*svy + svz*svz);
                float launchAngle = _activeProfile.OutputLaunchAngle
                    ? MathF.Atan2(svy, MathF.Sqrt(svx*svx + svz*svz)) * 180f / MathF.PI
                    : 0f;

                // Average detection confidence with triangulation confidence
                float detConf = det0 != null && det1 != null
                    ? (det0.Confidence + det1.Confidence) * 0.5f
                    : (det0?.Confidence ?? det1?.Confidence ?? 0f);
                float finalConf = (detConf + pt3d.Confidence) * 0.5f;

                long ts = det0?.TimestampUs ?? det1?.TimestampUs
                    ?? DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() * 1000;

                var ballData = new BallData
                {
                    SportId        = _activeProfile.SportId,
                    TimestampUs    = ts,
                    PosX = sx, PosY = sy, PosZ = sz,
                    VelX = svx, VelY = svy, VelZ = svz,
                    SpeedMps       = speed,
                    LaunchAngleDeg = launchAngle,
                    SpinRpm        = _activeProfile.OutputSpin ? EstimateSpin(speed) : 0f,
                    Confidence     = finalConf,
                    TrackingTier   = (int)pt3d.Tier
                };

                _udp?.Send(ballData);
            }
        }

        // Placeholder spin — replace with optical flow between frames
        private float EstimateSpin(float speedMps) => speedMps * 30f;

        public void Stop() => _running = false;
        public void Dispose() { Stop(); _cameras.Dispose(); _udp?.Dispose(); }
    }
}