// ------------------------------------------------------------
// App/SimulatorEngine.cs
// ------------------------------------------------------------
using System;
using System.Collections.Generic;
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Structure;
using SportSimulator.Models;
using SportSimulator.Profiles;
using SportSimulator.Tracking;
using SportSimulator.Transport;
using SportSimulator.Vision;
using SportSimulator.Vision.Calibration;

namespace SportSimulator.App
{
    public class SimulatorEngine : IDisposable
    {
        private readonly ICameraManager    _cameras;
        private readonly BallDetector      _detector = new();
        private readonly KalmanBallTracker _tracker = new();
        private readonly SportProfileRegistry _registry = new();
        private readonly StereoRectifier _rectifier = new();
        private readonly Triangulator    _triangulator = new();
        private readonly SpinEstimator   _spinEstimator = new();
        private readonly Spin3DEstimator _spin3DEstimator;

        /// <summary>
        /// Production constructor — uses the real Spinnaker-backed CameraManager.
        /// Only available on net48 (Spinnaker SDK is not present on net10.0).
        /// </summary>
#if NET48
        public SimulatorEngine() : this(new CameraManager()) { }
#endif

        /// <summary>
        /// Injection constructor — pass a MockCameraManager (or any ICameraManager)
        /// for unit tests on machines without the Spinnaker SDK.
        /// </summary>
        public SimulatorEngine(ICameraManager cameras)
        {
            _cameras = cameras;
            _activeProfile = _registry.GetOrDefault("soccer");
            _spin3DEstimator = new Spin3DEstimator(_triangulator);
        }

        private UdpTransport? _udp;
        private SportProfile  _activeProfile = null!; // set in constructor before use
        private bool _running;

        // Latest detection from each camera, keyed by camera index
        private readonly Dictionary<int, DetectionResult> _pending = new();
        private readonly object _pendingLock = new();

        // Max frames the Kalman filter will predict forward without any detection.
        // Set from SportProfile.KalmanCoastFrames on each profile switch.
        private int _maxCoastFrames = 5;
        private int _coastFrames = 0;

        // Most recent ball crop seen per camera, for frame-to-frame spin correlation.
        // Keyed by CameraIndex. See SpinEstimator.cs for method + current limits
        // (reliable for soccer's spin rates at 120fps; not yet for golf/baseball/tennis).
        private readonly Dictionary<int, (byte[] crop, int size, long timestampUs)> _lastCrop = new();
        private float _lastSpinRpm = 0f;

        // Full 3D spin (magnitude + axis) via natural-texture point tracking —
        // see Vision/Spin3DEstimator.cs. Only runs when both cameras detected the
        // ball this cycle (needs a stereo pair for triangulation). Takes priority
        // over the single-camera 2D SpinEstimator above when it produces a valid
        // fit; the 2D estimate remains as a magnitude-only fallback otherwise
        // (e.g. too few tracked/matched points this cycle).
        // AxisUnit is camera-relative, NOT yet rotated into shot-relative
        // backspin/sidespin terms — see Spin3DEstimator.cs class comment.
        private Vec3 _lastSpinAxis = default;
        private int  _logFrameCounter = 0;

        // Calibration file path — generated by running StereoCalibrator once.
        // ⚠️ SETUP TODO — run the calibration routine before first real use:
        //   1. Print a 9×6 checkerboard with 25mm squares
        //   2. Hold it at various positions/angles visible to both cameras
        //   3. Call StereoCalibrator.AddFramePair() for 15+ positions
        //   4. Call StereoCalibrator.Calibrate() — outputs this JSON file
        //   5. Aim for RMS reprojection error < 1.0px (< 0.5px is excellent)
        // Until this file exists, CreateDefaults() is used as a fallback.
        private const string CalibPath = "stereo_calibration.json";

        public void Start(string unityIp = "127.0.0.1", int sendPort = 7100, int listenPort = 7101)
        {
            LoadCalibration();

            _udp = new UdpTransport(unityIp, sendPort, listenPort);
            _udp.ProfileCommandReceived += OnProfileCommand;
            _udp.StartListening();

            _cameras.Initialize(_activeProfile.SportId);
            ApplyProfile(_activeProfile);
            _cameras.StartCapture();

            _running = true;
            Console.WriteLine("[Engine] Running. Waiting for stereo frame pairs...");
            ProcessLoop();
        }

        private void LoadCalibration()
        {
            StereoCalibrationData cal;
            if (System.IO.File.Exists(CalibPath))
            {
                cal = StereoCalibrationData.LoadFromFile(CalibPath);
                Console.WriteLine($"[Engine] Loaded calibration from {CalibPath}");
            }
            else
            {
                // ⚠️ SETUP TODO — using estimated defaults until calibration is run.
                // Baseline measured at 19.5in center-to-center → 19.5 * 0.0254 = 0.4953m.
                // Sensor resolution/focal length below are still unconfirmed placeholders —
                // update once the checkerboard calibration (StereoCalibrator) has been run.
                cal = StereoCalibrationData.CreateDefaults(baselineMetres: 0.4953);
                Console.WriteLine("[Engine] WARNING: Using default calibration. Run StereoCalibrator for accuracy.");
            }

            _rectifier.Build(cal);
            _triangulator.Configure(cal);
        }

        private void OnProfileCommand(ProfileSelectCommand cmd)
        {
            var p = _registry.GetOrDefault(cmd.SportId);
            ApplyProfile(p);
            Console.WriteLine($"[Engine] Profile switched to: {p.DisplayName}");
        }

        private void ApplyProfile(SportProfile p)
        {
            _activeProfile  = p;
            _detector.SetProfile(p);
            _tracker.Configure(p);
            _cameras.ApplyProfile(p.SportId);
            _maxCoastFrames = p.KalmanCoastFrames;
            Console.WriteLine($"[Engine] Coast window set to {_maxCoastFrames} frames for {p.DisplayName}");
        }

        private void ProcessLoop()
        {
            while (_running)
            {
                // Drain all frames that arrived since last iteration
                DetectionResult? det0 = null, det1 = null;
                CameraFrame? rectFrame0 = null, rectFrame1 = null;

                while (_cameras.FrameQueue.TryTake(out var frame, 5))
                {
                    // Detection, triangulation (disparity + DLT via P0/P1), and
                    // stereo point-matching for 3D spin all assume RECTIFIED image
                    // coordinates — undistorted, with corresponding points on the
                    // same row between cameras. Rectify before anything else touches
                    // the frame.
                    var rectified = RectifyFrame(frame);
                    var det = _detector.Detect(rectified);
                    if (!det.Found) continue;
                    UpdateSpinEstimate(det);
                    if (det.CameraIndex == 0) { det0 = det; rectFrame0 = rectified; }
                    else                      { det1 = det; rectFrame1 = rectified; }
                }

                TriangulatedPoint? pt3d = null;

                // ── Tier 1 / 2: both cameras this cycle ─────────────────────────
                if (det0 != null && det1 != null)
                {
                    pt3d = _triangulator.TriangulateStereo(det0.Center, det1.Center);

                    // If stereo disagreed and fell to monocular internally,
                    // enrich it with the Kalman's last Z before sending
                    if (pt3d.Tier == TriangulationTier.Monocular && pt3d.Z == 0)
                    {
                        var (kx, ky, kz, _, _, _) = _tracker.LastState;
                        pt3d = _triangulator.TriangulateMonocular(det0.Center, kz);
                    }

                    UpdateSpin3D(rectFrame0!, rectFrame1!, det0, pt3d);

                    _coastFrames = 0;
                }
                // ── Tier 3: only one camera this cycle ──────────────────────────
                else if (det0 != null || det1 != null)
                {
                    var single = (det0 ?? det1)!;
                    var (_, _, kz, _, _, _) = _tracker.LastState;
                    pt3d = _triangulator.TriangulateMonocular(single.Center, kz);
                    _coastFrames = 0;
                }
                // ── Tier 4: no detection — Kalman coast ─────────────────────────
                else
                {
                    _coastFrames++;
                    if (_coastFrames > _maxCoastFrames) continue; // ball gone

                    var (kx, ky, kz, _, _, _) = _tracker.LastState;
                    float coastConf = Math.Max(0.05f, 0.3f - _coastFrames * (0.25f / _maxCoastFrames));
                    pt3d = new TriangulatedPoint
                    {
                        X = kx, Y = ky, Z = kz,
                        Confidence = coastConf,
                        Tier       = TriangulationTier.KalmanOnly,
                        TierReason = $"Coasting frame {_coastFrames}/{_maxCoastFrames}"
                    };
                }

                // Flip Y: OpenCV Y-down → Unity Y-up
                float mx = pt3d.X, my = -pt3d.Y, mz = pt3d.Z;

                // Only feed real measurements into Kalman; coast uses predict-only
                (float x, float y, float z, float vx, float vy, float vz) state;
                if (pt3d.Tier == TriangulationTier.KalmanOnly)
                    state = _tracker.Predict();
                else
                    state = _tracker.Update(mx, my, mz);

                var (sx, sy, sz, svx, svy, svz) = state;
                float speed       = MathF.Sqrt(svx*svx + svy*svy + svz*svz);
                float launchAngle = _activeProfile.OutputLaunchAngle
                    ? MathF.Atan2(svy, MathF.Sqrt(svx*svx + svz*svz)) * 180f / MathF.PI
                    : 0f;

                // Average detection confidence with triangulation confidence
                float detConf = det0 != null && det1 != null
                    ? (det0.Confidence + det1.Confidence) * 0.5f
                    : (det0?.Confidence ?? det1?.Confidence ?? 0f);
                float finalConf = (detConf + pt3d.Confidence) * 0.5f;

                long ts = det0?.TimestampUs ?? det1?.TimestampUs
                    ?? DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() * 1000;

                var ballData = new BallData
                {
                    SportId        = _activeProfile.SportId,
                    TimestampUs    = ts,
                    PosX = sx, PosY = sy, PosZ = sz,
                    VelX = svx, VelY = svy, VelZ = svz,
                    SpeedMps       = speed,
                    LaunchAngleDeg = launchAngle,
                    SpinRpm        = _activeProfile.OutputSpin ? _lastSpinRpm : 0f,
                    SpinAxisX      = _activeProfile.OutputSpin ? _lastSpinAxis.X : 0f,
                    SpinAxisY      = _activeProfile.OutputSpin ? _lastSpinAxis.Y : 0f,
                    SpinAxisZ      = _activeProfile.OutputSpin ? _lastSpinAxis.Z : 0f,
                    Confidence     = finalConf,
                    TrackingTier   = (int)pt3d.Tier
                };

                _udp?.Send(ballData);

                // Throttled trajectory readout — at ~200fps, logging every frame
                // would be an unreadable firehose; every 20th frame is still a live
                // ~10Hz readout while testing, without flooding the console.
                if (++_logFrameCounter % 20 == 0)
                {
                    Console.WriteLine(
                        $"[Ball] pos=({sx:F2},{sy:F2},{sz:F2}) speed={speed:F1}m/s tier={pt3d.Tier} " +
                        $"conf={finalConf:F2} spin={_lastSpinRpm:F0}rpm axis=({_lastSpinAxis.X:F2},{_lastSpinAxis.Y:F2},{_lastSpinAxis.Z:F2})");
                }
            }
        }

        // Apply the stereo undistort+rectify maps (built once in LoadCalibration)
        // to a raw captured frame. Same Mat<->byte[] round-trip pattern used
        // elsewhere in this codebase (BallDetector.ExtractCrop, KalmanBallTracker).
        private CameraFrame RectifyFrame(CameraFrame frame)
        {
            using var raw = new Mat(frame.Height, frame.Width, DepthType.Cv8U, 1);
            raw.SetTo(frame.Data);
            using var rectified = _rectifier.Rectify(raw, frame.CameraIndex);

            using var m = new Matrix<byte>(rectified.Rows, rectified.Cols);
            rectified.CopyTo(m.Mat);
            var bytes = new byte[rectified.Rows * rectified.Cols];
            for (int r = 0; r < rectified.Rows; r++)
                for (int c = 0; c < rectified.Cols; c++)
                    bytes[r * rectified.Cols + c] = m[r, c];

            return new CameraFrame
            {
                CameraIndex    = frame.CameraIndex,
                Data           = bytes,
                Width          = rectified.Cols,
                Height         = rectified.Rows,
                TimestampUs    = frame.TimestampUs,
                ExposureTimeUs = frame.ExposureTimeUs,
                GainDb         = frame.GainDb
            };
        }

        // Full 3D spin (magnitude + axis) — only possible when both cameras
        // detected the ball this cycle, since it needs a stereo pair to
        // triangulate tracked feature points. Falls through silently (leaving
        // _lastSpinRpm/_lastSpinAxis at their previous values) when the fit isn't
        // valid this frame — UpdateSpinEstimate's single-camera 2D magnitude-only
        // fallback keeps running independently either way.
        private void UpdateSpin3D(CameraFrame leftFrame, CameraFrame rightFrame, DetectionResult det0, TriangulatedPoint pt3d)
        {
            if (!_activeProfile.OutputSpin) return;

            using var leftMat  = FrameToMat(leftFrame);
            using var rightMat = FrameToMat(rightFrame);

            var m = _spin3DEstimator.Update(leftMat, rightMat, det0.Center, det0.RadiusPx,
                                             pt3d.Disparity, leftFrame.TimestampUs);
            if (!m.Valid) return;

            _lastSpinRpm  = m.Rpm;
            _lastSpinAxis = m.AxisUnit;

            // Unthrottled, unlike the general trajectory log below — how OFTEN this
            // line appears at all is itself the key diagnostic for whether natural-
            // texture tracking is finding enough points on your real ball surfaces
            // (see Vision/FeaturePointTracker.cs). Axis is camera-relative, not yet
            // rotated into backspin/sidespin terms — see Vision/Spin3DEstimator.cs.
            Console.WriteLine($"[Spin3D] rpm={m.Rpm:F0} axis=({m.AxisUnit.X:F2},{m.AxisUnit.Y:F2},{m.AxisUnit.Z:F2}) points={m.PointsUsed}");
        }

        private static Mat FrameToMat(CameraFrame frame)
        {
            var m = new Mat(frame.Height, frame.Width, DepthType.Cv8U, 1);
            m.SetTo(frame.Data);
            return m;
        }

        // Correlate this detection's crop against the last one seen from the SAME
        // camera to estimate rotation. Pairs more than 50ms apart (dropped frame,
        // coast gap, camera switch) are skipped rather than fed to the estimator —
        // the rotation-search range assumes near-consecutive frames.
        private void UpdateSpinEstimate(DetectionResult det)
        {
            if (!_activeProfile.OutputSpin || det.Crop == null) return;

            if (_lastCrop.TryGetValue(det.CameraIndex, out var prev) && prev.size == det.CropSize)
            {
                float dt = (det.TimestampUs - prev.timestampUs) / 1_000_000f;
                if (dt > 0f && dt < 0.05f)
                {
                    var m = _spinEstimator.Estimate(prev.crop, det.Crop, det.CropSize, dt);
                    if (m.Valid) _lastSpinRpm = m.Rpm;
                }
            }

            _lastCrop[det.CameraIndex] = (det.Crop, det.CropSize, det.TimestampUs);
        }

        public void Stop() => _running = false;
        public void Dispose() { Stop(); _cameras.Dispose(); _udp?.Dispose(); }
    }
}